services:
  # PHP-FPM + Supervisor + Cron
  php-app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      args:
        user: '${CONTAINER_USER}'
        uid: '${CONTAINER_USER_ID}'
        group: '${CONTAINER_GROUP}'
        guid: '${CONTAINER_GROUP_ID}'
    container_name: '${APP_CONTAINER_NAME}'
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      # Laravel kodingiz hostdan ko‘rinsin:
      - ./src/:/var/www/html/src
      # PHP-FPM loglari:
      - ./docker/logs/php-fpm:/var/log/php-fpm
    networks:
      - app-network
    depends_on:
      - laravel-ai-db
      - ollama
    environment:
      OLLAMA_URL: "http://ollama:11434"
      DEFAULT_MODEL: "gpt-oss:20b"
      EMBED_MODEL: "nomic-embed-text"

  # Postgres + pgvector (RAG uchun shart)
  laravel-ai-db:
    image: pgvector/pgvector:pg17
    container_name: laravel-ai-db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - migrant-pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Nginx (public: 84/444)
  nginx-server:
    image: nginx:alpine
    container_name: '${NGINX_CONTAINER_NAME}'
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/logs/nginx:/var/log/nginx
    networks:
      - app-network
    environment:
      - APP_CONTAINER_NAME=${APP_CONTAINER_NAME}
      - FPM_PATH=${FPM_PATH}
      - SERVER_NAME=${DOMAIN_NAME}
    depends_on:
      - php-app

  # Redis (optional)
  cache-redis:
    image: redis:alpine
    container_name: '${REDIS_CONTAINER_NAME}'
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network

  # Ollama (LLM + Embeddings)
  ollama:
    image: ollama/ollama:latest
    container_name: laravel-ai-ollama
    restart: unless-stopped
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 5s
      retries: 20

# Volumes
volumes:
  migrant-pgdata:
    driver: local
  ollama_models:
    driver: local

# Networks
networks:
  app-network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
